name: Set up Node.js and MongoDB

on:
  workflow_call:

env:
  PORT: 3000
  MONGODB_URL: mongodb://127.0.0.1:27017/node-ts-boilerplate
  JWT_SECRET: thisisasamplesecret
  JWT_ACCESS_EXPIRATION_MINUTES: 30
  JWT_REFRESH_EXPIRATION_DAYS: 30
  JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
  JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: yarn